name: Build

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2
      
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.4.0

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.4.0
        env:
          CIBW_ARCHS_LINUX: x86_64 aarch64

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
